branch-defaults:
  eb:
    environment: null
    group_suffix: null
global:
  application_name: sample
  branch: null
  default_ec2_keyname: flyer_keypair.pem
  default_platform: docker
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
